# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeBirthday' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeBirthday
  pod 'AppCenter/Push', '~> 1.1.0'
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  pod 'react-native-add-calendar-event', :path => '../node_modules/react-native-add-calendar-event'

  target 'AwesomeBirthdayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AwesomeBirthday-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeBirthday-tvOS

  target 'AwesomeBirthday-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
